# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f4b6c78b938690b235f537164fd971a3a6a4081e7b2859fc56fc00dd20dd3900a0a09642f6f8e003b394c555960de51dae5edd0855cf693a517fe973ebb13e4

test:
  secret_key_base: dbffd4dfcd4ce427b9c869c0d190cd81af63a63d792612d940c09061e9f2a9be75b359608f7040c4cc88700e5d749156ae35f0d715dda5dee378e3bad08a5696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
