# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9735108ac4f143556cf750169f35ee51a2e6d5db76ec67832424b0c138344935eee7a034a940aa01ebf16433526ba910144cc7c3084d0751d285596f72ac987

test:
  secret_key_base: 3b2c238167035fb5d7f5885607a30d2ce087f1db5524915c9d82d09ec0ff5639e3505692f822e6ebf6a06d5bae2f182379984607d025dc12034b3666ee9f68c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
